### ISSUE TITLE
Create first release for echoregions

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoregions#68]
It'll be good in the not too distant future to create a release for echoregions that contains stable basic functionalities. We can set up the releases to publish directly to PyPI and triggered a conda build (#67). 

IMHO we should do this _after_ resolving things in #54 so things are not that confusing.

### Tasks
- [x] Set up webhook for Zenodo
- [ ] Do slight refactoring so as to match what is found in [Scientific Python](https://learn.scientific-python.org/development/) and [Python Packaging](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
- [ ] Create release on GitHub
- [ ] Submit to test PyPI
- [ ] Submit to official PyPI
- [ ] Ensure can pip install directly from PyPI
- [ ] Update pip install instructions in docs to use pypi

**Comment by ctuguinay** [comment]
- [ ] Add conda environment file for general use

**Comment by leewujung** [comment]
Seems like all of the tasks here have been either completed or captured in #116. Closing this now.
